config/routes.rb
Timecard::Application.routes.draw do

  resources :users, only: %i(new create update) do
    member do
      get :home
      get :lab
      get :out
      get :disable
      get :remove_attendance_plan
    end

    collection do
      get :dismiss
    end
  end

  root 'index#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :activities

  default_scope { order('yomi ASC') }
  scope :working, -> { where(status: 1) }

  def status_to_str
    case self.status
    when 0
      '帰宅'
    when 1
      '実験中'
    when 2
      '離席'
    when 3
      '出勤不能'
    end
  end

  def lab
    self.activities.create!(activity_type: 1)
    self.status = 1
    self.save!
  end

  def home
    self.activities.create!(activity_type: 0)
    self.status = 0
    self.save!
  end

  def out
    self.activities.create!(activity_type: 2)
    self.status = 2
    self.save!
  end

  def disable
    self.activities.create!(activity_type: 3)
    self.status = 3
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with :name => APP_CONFIG['username'], :password => APP_CONFIG['password']
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @users = User.all
    @working = User.working
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(lab home out disable update remove_attendance_plan)

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: '登録しました。'
    else
      render action: :new
    end
  end

  def lab
    @user.lab
    redirect_to root_path, notice: 'In the fields of observation chance favors only those minds which are prepared.'
  end

  def home
    @user.home
    redirect_to root_path, notice: 'お疲れ様でした'
  end

  def out
    @user.out
    redirect_to root_path, notice: '休息も仕事のうち'
  end

  def disable
    @user.disable
    redirect_to root_path, notice: 'この分はいつ働いてもらおうかしらね…'
  end

  def update
    @user.attributes = user_params
    @user.save!
    redirect_to root_path, notice: '出勤予定を設定しました。'
  end

  def remove_attendance_plan
    @user.attendance_plan = nil
    @user.save
    redirect_to root_path, notice: '出勤予定を削除しました。'
  end

  def dismiss
    User.working.each do |u|
      u.home
    end
    redirect_to root_path, notice: 'お疲れ様でした'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit %i(name yomi attendance_plan)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def status_with_color(user)
    label_type = case user.status
                 when 0
                   ""
                 when 1
                   "label-success"
                 when 2
                   "label-warning"
                 end
    content_tag(:span, user.status_to_str, class: "label #{label_type}")
  end
end

app/views/index/index.html.haml
#working
  %h3 実験中のメンバー
  = link_to('解散', dismiss_users_path, class: "btn")
  %ul
    - @working.each do |u|
      %li= u.name

#members
  %h3 メンバー一覧
  %table.table
    %tr
      %th 氏名
      %th 現在の状態
      %th 状態を変更
      %th 次回出勤予定

    - @users.each do |u|
      %tr
        %td= u.name
        %td= status_with_color(u)
        %td
          = link_to('実験中',   u.status != 1 ? lab_user_path(u)  :    'javascript:void(0)', class: "btn btn-success #{ u.status != 1 ? '' : 'disabled'}")
          = link_to('離席',     u.status == 1 ? out_user_path(u)  :    'javascript:void(0)', class: "btn btn-warning #{ u.status == 1 ? '' : 'disabled'}")
          = link_to('帰宅',     u.status != 0 ? home_user_path(u) :    'javascript:void(0)', class: "btn btn-danger  #{ u.status != 0 ? '' : 'disabled'}")
          = link_to('出勤不能', u.status != 3 ? disable_user_path(u) : 'javascript:void(0)', class: "btn             #{ u.status != 3 ? '' : 'disabled'}")
        %td
          = u.attendance_plan.strftime("%Y-%m-%d %H:%M") if u.attendance_plan
          = link_to('出勤予定削除', remove_attendance_plan_user_path(u), class: "btn") if u.attendance_plan
          %button.js-add-attendance-plan.btn.pull-right 設定
          = simple_form_for u do |f|
            = f.input :attendance_plan, label: false, as: :datetime, datetime_separator: ''
            = f.button :submit, 'Save'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "iGEM Timecard"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{:href => "#"} Timecard
          .container
            %ul.nav
              %li= link_to "メンバー登録", new_user_path
          / /.nav-collapse
    .container
      .row
        .span12
          = bootstrap_flash
          = yield
        / /span
      / /row
      %footer
        %p &copy; iTakeshi 2013
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/users/new.html.haml
%h1 メンバー登録
= simple_form_for @user, html: { class: 'form-horizontal' } do |f|
  %fieldset
    = f.input :name, hint: "例: 山田太郎"
    = f.input :yomi, hint: "例: やまだ たろう"
    .form-actions
      = f.button :submit, class: 'btn-primary'